spring.application.name=gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Rutas existentes
spring.cloud.gateway.mvc.routes[0].id=descuentos
spring.cloud.gateway.mvc.routes[0].uri=lb://ms_discount
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/descuentos/**,/api/v1/discounts/**

spring.cloud.gateway.mvc.routes[1].id=pagos
spring.cloud.gateway.mvc.routes[1].uri=lb://ms-pagos
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/pagos/**

spring.cloud.gateway.mvc.routes[2].id=catalogo
spring.cloud.gateway.mvc.routes[2].uri=lb://ms-productos
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/productos/**

spring.cloud.gateway.mvc.routes[3].id=carrito
spring.cloud.gateway.mvc.routes[3].uri=lb://ms-carrito
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/v1/carrito/**

spring.cloud.gateway.mvc.routes[4].id=envios
spring.cloud.gateway.mvc.routes[4].uri=lb://ms-envios
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/v1/envios/**

spring.cloud.gateway.mvc.routes[5].id=orders
spring.cloud.gateway.mvc.routes[5].uri=lb://ms-order
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/v1/orders/**

spring.cloud.gateway.mvc.routes[6].id=reviews
spring.cloud.gateway.mvc.routes[6].uri=lb://ms-reviews
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/v1/reviews/**

spring.cloud.gateway.mvc.routes[7].id=subscriptions
spring.cloud.gateway.mvc.routes[7].uri=lb://ms-subscriptions
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/api/v1/subscriptions/**

spring.cloud.gateway.mvc.routes[8].id=tickets
spring.cloud.gateway.mvc.routes[8].uri=lb://ms-tickets
spring.cloud.gateway.mvc.routes[8].predicates[0]=Path=/api/v1/tickets/**

spring.cloud.gateway.mvc.routes[9].id=users
spring.cloud.gateway.mvc.routes[9].uri=lb://ms-users
spring.cloud.gateway.mvc.routes[9].predicates[0]=Path=/api/v1/user/**,/api/v1/admin/**,/api/v1/auth/**

spring.cloud.gateway.mvc.routes[10].id=wishlist
spring.cloud.gateway.mvc.routes[10].uri=lb://ms-wishlist
spring.cloud.gateway.mvc.routes[10].predicates[0]=Path=/api/v1/wishlist/**

spring.cloud.loadbalancer.ribbon.enabled=false
spring.cloud.gateway.mvc.http.client.type=simple
spring.cloud.loadbalancer.eureka.approximateZoneFromHostname=true