spring.application.name=ms-tickets
server.port=9096

# Nivel global
logging.level.root=INFO

# Tu package
logging.level.com.example.ms_tickets=DEBUG

# Archivo de logs
logging.file.name=logs/ms-tickets.log


spring.datasource.url=jdbc:mysql://localhost:3306/db_ticket
spring.datasource.username=root
spring.datasource.password=

#JPA/Hibernate
#preguntar
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=una_clave_secreta_larga_y_segura_de_al_menos_32_bytes
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true